### ISSUE TITLE
Firefox Browser for Internet Explorer Custom Launcher

### ISSUE THREAD

**Issue by alwinmark** [saucelabs/karma-sauce-example#6]
Hi,

I want to ask, if this is done by Copy n' Paste error or by purpose:
https://github.com/saucelabs/karma-sauce-example/blob/master/karma.conf-ci.js#L22

As you might see, these lines will configure, that SL_Firefox will be configured ad browser, but Internet Explorer is configured as Custom Launcher.

If this is indented I'm really interested in the reasons

**Comment by jcsrb** [comment]
@alwinmark looks like an error to me, take a look the the example config in this repo readme

https://github.com/karma-runner/karma-sauce-launcher/blob/master/README.md

**Comment by colinsauce** [comment]
hey @alwinmark that is a copy n paste error.

Thanks for catching it! I'm working on a PR right now to fix it.

**Comment by colinsauce** [comment]
merged that PR. Closing this.
